#!/usr/bin/env node

/**
 * Module dependencies.
 */

import program from '../lib';

program
    .option('-f, --foo', 'enable some foo')
    .option('-b, --bar', 'enable some bar')
    .option('-B, --baz', 'enable some baz');

// must be before .parse() since
// node's emit() is immediate

program.on('help', () => {
    console.log();
    console.log('  Examples:');
    console.log();
    console.log('    $ custom-help --help');
    console.log('    $ custom-help -h');
});

program.parse(process.argv);

program.help();
