#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('../');

function list(val) {
    return val.split(',').map(Number);
}

program
    .option('-t, --template-engine [engine]', 'Add template [engine] support', 'jade')
    .option('-c, --cheese [type]', 'Add the specified type of cheese [marble]', 'marble')
    .option('-l, --list [items]', 'Specify list items defaulting to 1,2,3', list, [1,2,3])
    .parse(process.argv);

var options = program.options;
console.log('  - %s template engine', options.templateEngine);
console.log('  - %s cheese', options.cheese);
console.log('  - %j', options.list);
