#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('../');

program
    .option('-s, --sessions', 'add session support')
    .option('-t, --template <engine>', 'specify template engine (jade|ejs) [jade]', 'jade')
    .option('-c, --css <engine>', 'specify stylesheet engine (stylus|sass|less) [css]', 'css')
    .parse(process.argv);

var options = program.options;
console.log(' - sessions %j', options.sessions);
console.log(' - template %j', options.template);
console.log(' - css %j', options.css);
