#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('../');

program
    .option('-f, --foo', 'enable some foo')
    .option('-b, --bar', 'enable some bar')
    .option('-B, --baz', 'enable some baz')
    .parse(process.argv);

if (!program.args.length) program.help();
