#!/usr/bin/env node

var program = require('..');

program
    .usage('pm-install <packages>...')
    .option('-f, --force', 'force installation')
    .parse(process.argv);

var pkgs = program.args.packages;

console.log();
if (program.options.force) console.log('  force: install');
pkgs.forEach(function(pkg){
    console.log('  install : %s', pkg);
});
console.log();
