#!/usr/bin/env node

import program from '../lib';

program
    .usage('pm-install <packages>...')
    .option('-f, --force', 'force installation')
    .parse(process.argv);

const pkgs = program.args.packages;

console.log();
if (program.options.force) console.log('  force: install');
pkgs.forEach((pkg) => {
    console.log('  install : %s', pkg);
});
console.log();
